DumpMemoryAllocator: operator==
Modern g++ versions require operator== and operator!= for the DumpMemoryAllocator.
Fixes:

    In file included from /usr/include/c++/13/list:65,
                     from emit-common.cpp:30:
    /usr/include/c++/13/bits/stl_list.h: In instantiation of 'void std::__cxx11::list<_Tp, _Alloc>::_M_check_equal_allocators(const std::__cxx11::list<_Tp, _Alloc>&) [with _Tp = branch_label_ref_t*; _Alloc = DumpMemoryAllocator<branch_label_ref_t*>]':
    /usr/include/c++/13/bits/stl_list.h:1668:4:   required from 'void std::__cxx11::list<_Tp, _Alloc>::splice(const_iterator, std::__cxx11::list<_Tp, _Alloc>&&, const_iterator) [with _Tp = branch_label_ref_t*; _Alloc = DumpMemoryAllocator<branch_label_ref_t*>; const_iterator = std::__cxx11::list<branch_label_ref_t*, DumpMemoryAllocator<branch_label_ref_t*> >::const_iterator]'
    /usr/include/c++/13/bits/stl_list.h:1690:15:   required from 'void std::__cxx11::list<_Tp, _Alloc>::splice(const_iterator, std::__cxx11::list<_Tp, _Alloc>&, const_iterator) [with _Tp = branch_label_ref_t*; _Alloc = DumpMemoryAllocator<branch_label_ref_t*>; const_iterator = std::__cxx11::list<branch_label_ref_t*, DumpMemoryAllocator<branch_label_ref_t*> >::const_iterator]'
    /usr/include/c++/13/bits/list.tcc:349:27:   required from 'std::__cxx11::list<_Tp, _Alloc>::__remove_return_type std::__cxx11::list<_Tp, _Alloc>::remove(const value_type&) [with _Tp = branch_label_ref_t*; _Alloc = DumpMemoryAllocator<branch_label_ref_t*>; __remove_return_type = void; value_type = branch_label_ref_t*]'
    emit-common.cpp:539:27:   required from here
    /usr/include/c++/13/bits/stl_list.h:2031:30: error: no match for 'operator!=' (operand types are 'std::__cxx11::_List_base<branch_label_ref_t*, DumpMemoryAllocator<branch_label_ref_t*> >::_Node_alloc_type' {aka 'std::allocator_traits<DumpMemoryAllocator<branch_label_ref_t*> >::rebind_alloc<std::_List_node<branch_label_ref_t*> >'} and 'const std::__cxx11::_List_base<branch_label_ref_t*, DumpMemoryAllocator<branch_label_ref_t*> >::_Node_alloc_type' {aka 'std::allocator_traits<DumpMemoryAllocator<branch_label_ref_t*> >::rebind_alloc<std::_List_node<branch_label_ref_t*> >'})

Upstream-Status: Submitted https://github.com/tekknolagi/cacao/pull/1
Signed-off-by: Douglas Royds <douglas.royds@taitcommunications.com>